CREATE TABLE `landing_page_analyses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`url` varchar(512) NOT NULL,
	`ad_group_name` varchar(255) NOT NULL,
	`campaign_name` varchar(255) NOT NULL,
	`pagespeed_mobile` int,
	`pagespeed_desktop` int,
	`lcp_ms` int,
	`cls_score` varchar(16),
	`page_title` varchar(512),
	`meta_description` text,
	`h1_text` varchar(512),
	`cta_text` varchar(255),
	`has_form` boolean DEFAULT false,
	`has_whatsapp` boolean DEFAULT false,
	`word_count` int,
	`group_ctr` varchar(16),
	`group_cpc` varchar(16),
	`group_conversions` int,
	`group_clicks` int,
	`group_spend` varchar(32),
	`diagnosis_score` int,
	`diagnosis_summary` text,
	`main_issues` json,
	`lovable_prompt` text,
	`priority` varchar(16) DEFAULT 'medium',
	`analyzed_at` timestamp NOT NULL DEFAULT (now()),
	`week_label` varchar(32) NOT NULL,
	CONSTRAINT `landing_page_analyses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `weekly_traffic_reviews` (
	`id` int AUTO_INCREMENT NOT NULL,
	`week_label` varchar(32) NOT NULL,
	`total_spend` varchar(32),
	`total_clicks` int,
	`total_impressions` int,
	`total_conversions` int,
	`avg_ctr` varchar(16),
	`avg_cpc` varchar(16),
	`executive_summary` text,
	`top_performers` json,
	`underperformers` json,
	`urgent_actions` json,
	`weekly_actions` json,
	`url_issues` json,
	`lp_insights` json,
	`pmax_ctr` varchar(16),
	`pmax_spend` varchar(32),
	`pmax_conversions` int,
	`pmax_diagnosis` text,
	`generated_at` timestamp NOT NULL DEFAULT (now()),
	`email_sent` boolean DEFAULT false,
	`status` varchar(16) DEFAULT 'pending',
	CONSTRAINT `weekly_traffic_reviews_id` PRIMARY KEY(`id`)
);
